FORMAT: 1A

# SourceGroups API
SourceGroups API is...

# Group SourceGroups
Notes related resources of the **SourceGroups API**

## SourceGroups Collection [/api/v1/sourcegroups]
### List all SourceGroups [GET]
+ Response 200 (application/json)

        [
            {
                "tenantId": "78facb56-f21c-40bb-9cb5-ddae78fb47b8",
                "name": "prod-web-server", 
                "description": "production web server",
                "query": "production web"
            },
            {
                "tenantId": "78facb56-f21c-40bb-9cb5-ddae78fb47b8",
                "name": "prod-database-server",
                "description": "production database server",
                "query": "production database"
            }
        ]

### Create a SourceGroup [POST]
+ Request (application/json)

        {
            "name": "stage-web-server",
            "description": "staging web server",
            "query": "staging web"
        }

+ Response 201 (application/json)

        {
            "tenantId": "78facb56-f21c-40bb-9cb5-ddae78fb47b8",
            "name": "stage-web-server",
            "description": "staging web server",
            "query": "staging web"
        }

## SourceGroup [/api/v1/sourcegroups/{name}]
A single SourceGroup object with all its details

+ Parameters
    + name (required, String, `prod-database-server`) ... String `name` of the SourceGroup to perform action with. Has example value.

### Retrieve a SourceGroup [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            {
                "tenantId": "78facb56-f21c-40bb-9cb5-ddae78fb47b8",
                "name": "prod-database-server",
                "description": "production database server",
                "query": "production database",
                "sources": [
                    {
                        "tenantId": "78facb56-f21c-40bb-9cb5-ddae78fb47b8",
                        "source": "meter-vm-1",
                        "products": [
                            "PULSE"
                        ],
                        "createdTimestamp": 1476118499000,
                        "receivedTimestamp": 1476118499862
                    }
                ]
            }

### Remove a SourceGroup [DELETE]
+ Response 204